create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  student_name text not null,
  school text not null,
  level text not null,
  course_format text not null default 'Cours collectif mini groupe',
  whatsapp text not null,
  city text not null,
  status text not null default 'pending',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  confirmed_at timestamptz
);

create table if not exists public.pricing (
  level text primary key,
  price integer not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.site_settings (
  id integer primary key,
  center_name text not null,
  direct_whatsapp text not null default '',
  professor_note text not null default '',
  maintenance_mode boolean not null default false,
  format_pricing_json text not null default '{}',
  course_formats_json text not null,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint site_settings_single_row check (id = 1)
);

create table if not exists public.push_subscriptions (
  endpoint text primary key,
  subscription_json text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.student_spaces (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null unique references public.reservations(id) on delete cascade,
  access_code text not null unique,
  portal_active boolean not null default true,
  individual_sessions_per_week integer not null default 1,
  course_ends_at timestamptz not null default '2026-07-11T23:59:59.000Z',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.student_portal_sessions (
  id bigint generated by default as identity primary key,
  student_space_id bigint not null references public.student_spaces(id) on delete cascade,
  title text not null,
  scheduled_at timestamptz not null,
  instructions text not null,
  file_url text not null default '',
  status text not null default 'scheduled',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.student_portal_tasks (
  id bigint generated by default as identity primary key,
  student_space_id bigint not null references public.student_spaces(id) on delete cascade,
  title text not null,
  due_at timestamptz not null,
  details text not null,
  file_url text not null default '',
  status text not null default 'todo',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists reservations_created_at_idx on public.reservations (created_at desc);
create index if not exists reservations_status_idx on public.reservations (status);

alter table public.site_settings add column if not exists center_address text default '';
alter table public.site_settings add column if not exists maps_url text default '';
alter table public.site_settings add column if not exists direct_whatsapp text not null default '';
alter table public.site_settings add column if not exists professor_note text not null default '';
alter table public.site_settings add column if not exists maintenance_mode boolean not null default false;
alter table public.site_settings alter column center_address set default '';
alter table public.site_settings alter column maps_url set default '';
update public.site_settings
set center_address = coalesce(center_address, ''),
    maps_url = coalesce(maps_url, '')
where id = 1;
alter table public.site_settings alter column center_address drop not null;
alter table public.site_settings alter column maps_url drop not null;

alter table public.admins enable row level security;
alter table public.reservations enable row level security;
alter table public.pricing enable row level security;
alter table public.site_settings enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.student_spaces enable row level security;
alter table public.student_portal_sessions enable row level security;
alter table public.student_portal_tasks enable row level security;
